# Managed by chezmoi. Edits here are overwritten by chezmoi apply.
# Edit the source instead:  chezmoi edit ~/.config/mise/config.toml
[settings]
idiomatic_version_file_enable_tools = ["node", "go"]

[tools]
go = "1.24"
node = "latest"
